"""add new field to cursos

Revision ID: 00f82b7c5def
Revises: 1093bbecf06f
Create Date: 2026-07-08 22:39:56.565971

"""
from alembic import op
import sqlalchemy as sa


revision = '00f82b7c5def'
down_revision = '1093bbecf06f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    inspector = sa.inspect(op.get_bind())
    columns = {column['name'] for column in inspector.get_columns('cursos')}
    if 'fin' not in columns:
        op.add_column('cursos', sa.Column('fin', sa.DateTime(), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cursos', 'fin')

    # ### end Alembic commands ###
