"""change schema cursos

Revision ID: 1093bbecf06f
Revises: 4b853775bc2b
Create Date: 2026-07-07 21:42:55.223178

"""
from alembic import op
import sqlalchemy as sa


revision = '1093bbecf06f'
down_revision = '4b853775bc2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
