"""campos opcionales

Revision ID: 25846d722221
Revises: 2e17db85e86e
Create Date: 2026-07-07 19:09:35.063375

"""
from alembic import op
import sqlalchemy as sa


revision = '25846d722221'
down_revision = '2e17db85e86e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
