"""migracion periodos flash

Revision ID: 2e17db85e86e
Revises: 4182c6d1369a
Create Date: 2026-07-07 18:54:58.880242

"""


revision = '2e17db85e86e'
down_revision = '4182c6d1369a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
