"""add fields to cursos

Revision ID: 2f2ca0e41647
Revises: 4f4c8ef54726
Create Date: 2026-07-02 20:25:00.479321

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = '2f2ca0e41647'
down_revision = '4f4c8ef54726'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    cursos_columns = {
        column['name'] for column in sa.inspect(op.get_bind()).get_columns('cursos')
    }
    if 'archivo' not in cursos_columns:
        op.add_column('cursos', sa.Column('archivo', sa.String(), nullable=True))
    if 'formulario' not in cursos_columns:
        op.add_column('cursos', sa.Column('formulario', sa.String(), nullable=True))
    op.alter_column('documentacion', 'tipo',
               existing_type=postgresql.ENUM('metodologia', 'codigo', 'manual', name='tipoenum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documentacion', 'tipo',
               existing_type=postgresql.ENUM('metodologia', 'codigo', 'manual', name='tipoenum'),
               nullable=False)
    op.drop_column('cursos', 'formulario')
    op.drop_column('cursos', 'archivo')
    # ### end Alembic commands ###
