"""eliminacion peridicidad

Revision ID: 3a3bab96269b
Revises: 00f82b7c5def
Create Date: 2026-07-13 16:18:08.628459

"""
from alembic import op
import sqlalchemy as sa


revision = '3a3bab96269b'
down_revision = '00f82b7c5def'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('DROP TABLE IF EXISTS documentacion_proyectos')
    op.execute('DROP INDEX IF EXISTS ix_proyectos_id')
    op.execute('DROP TABLE IF EXISTS proyectos')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proyectos',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('proyectos_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('slug', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='proyectos_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_proyectos_id', 'proyectos', ['id'], unique=False)
    op.create_table('documentacion_proyectos',
    sa.Column('documentacion_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('proyecto_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['documentacion_id'], ['documentacion.id'], name='documentacion_proyectos_documentacion_id_fkey'),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], name='documentacion_proyectos_proyecto_id_fkey'),
    sa.PrimaryKeyConstraint('documentacion_id', 'proyecto_id', name='documentacion_proyectos_pkey')
    )
    # ### end Alembic commands ###
