"""reconcilia esquema con modelos

Revision ID: 3c59a2cbf559
Revises: 6e5f4fe49b6c
Create Date: 2026-08-06 23:13:52.100302

"""
from alembic import op
import sqlalchemy as sa


revision = '3c59a2cbf559'
down_revision = '6e5f4fe49b6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('docs_iieg', 'descripcion',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('preguntas', 'slug',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.add_column('sistemas', sa.Column('slider', sa.Boolean(), nullable=True))
    op.add_column('sistemas', sa.Column('imagen_slider', sa.String(), nullable=True))
    op.alter_column('sistemas', 'slug',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sistemas', 'slug',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_column('sistemas', 'imagen_slider')
    op.drop_column('sistemas', 'slider')
    op.alter_column('preguntas', 'slug',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('docs_iieg', 'descripcion',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
