"""reconcilia esquema con modelos

Revision ID: 3c59a2cbf559
Revises: 6e5f4fe49b6c
Create Date: 2026-08-06 23:13:52.100302

"""
import sqlalchemy as sa

from alembic import op

revision = '3c59a2cbf559'
down_revision = '6e5f4fe49b6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    inspector = sa.inspect(op.get_bind())
    docs_columns = {column['name']: column for column in inspector.get_columns('docs_iieg')}
    if 'descripcion' in docs_columns and not docs_columns['descripcion']['nullable']:
        op.alter_column('docs_iieg', 'descripcion', existing_type=sa.TEXT(), nullable=True)

    preguntas_columns = {column['name']: column for column in inspector.get_columns('preguntas')}
    if 'slug' in preguntas_columns and not preguntas_columns['slug']['nullable']:
        op.alter_column('preguntas', 'slug', existing_type=sa.VARCHAR(length=200), nullable=True)

    sistemas_columns = {column['name']: column for column in inspector.get_columns('sistemas')}
    if 'slider' not in sistemas_columns:
        op.add_column('sistemas', sa.Column('slider', sa.Boolean(), nullable=True))
    if 'imagen_slider' not in sistemas_columns:
        op.add_column('sistemas', sa.Column('imagen_slider', sa.String(), nullable=True))
    if 'slug' in sistemas_columns and not sistemas_columns['slug']['nullable']:
        op.alter_column('sistemas', 'slug', existing_type=sa.VARCHAR(length=200), nullable=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sistemas', 'slug',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_column('sistemas', 'imagen_slider')
    op.drop_column('sistemas', 'slider')
    op.alter_column('preguntas', 'slug',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('docs_iieg', 'descripcion',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
