"""add field to cursos

Revision ID: 4182c6d1369a
Revises: 2f2ca0e41647
Create Date: 2026-07-03 16:14:00.137336

"""


revision = '4182c6d1369a'
down_revision = '2f2ca0e41647'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
