"""make flashes fields nullable

Revision ID: 4b853775bc2b
Revises: 25846d722221
Create Date: 2026-07-07 19:25:01.940798

"""


revision = '4b853775bc2b'
down_revision = '25846d722221'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
