"""campos de tipo

Revision ID: 4f4c8ef54726
Revises: merge_zz_ffcbb
Create Date: 2026-06-17 21:36:53.495952

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '4f4c8ef54726'
down_revision = 'merge_zz_ffcbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentacion', sa.Column('anyo', sa.Integer(), nullable=True))
    op.add_column('documentacion', sa.Column('archivo', sa.String(), nullable=True))
    # create enum type 'tipoenum' before adding the column
    tipo_enum = sa.Enum('metodologia', 'codigo', 'manual', name='tipoenum')
    tipo_enum.create(op.get_bind(), checkfirst=True)
    # add column as nullable, migrate values from legacy columns, then make it NOT NULL
    op.add_column('documentacion', sa.Column('tipo', tipo_enum, nullable=True))
    # migrate values: prefer existing 'metodologia' or 'codigo' columns
    op.execute("""
    UPDATE documentacion SET tipo = 'metodologia' WHERE metodologia IS NOT NULL AND metodologia <> '';
    UPDATE documentacion SET tipo = 'codigo' WHERE codigo IS NOT NULL AND codigo <> '' AND (tipo IS NULL OR tipo::text = '');
    UPDATE documentacion SET tipo = 'manual' WHERE tipo IS NULL OR tipo::text = '';
    """)
    op.drop_column('documentacion', 'codigo')
    op.drop_column('documentacion', 'metodologia')
    # now set column to NOT NULL
    op.alter_column('documentacion', 'tipo', existing_type=tipo_enum, nullable=False)
    # create enum type 'mesenum' before adding the column
    mes_enum = sa.Enum('enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre', name='mesenum')
    mes_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('flashes', sa.Column('mes', mes_enum, nullable=True))
    op.add_column('flashes', sa.Column('anyo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flashes', 'anyo')
    op.drop_column('flashes', 'mes')
    op.add_column('documentacion', sa.Column('metodologia', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documentacion', sa.Column('codigo', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # try to restore legacy columns from 'tipo' where possible
    op.execute("""
    UPDATE documentacion SET metodologia = '' WHERE metodologia IS NULL;
    UPDATE documentacion SET codigo = '' WHERE codigo IS NULL;
    UPDATE documentacion SET metodologia = '' WHERE tipo = 'metodologia';
    UPDATE documentacion SET codigo = '' WHERE tipo = 'codigo';
    """)
    op.drop_column('documentacion', 'tipo')
    op.drop_column('documentacion', 'archivo')
    op.drop_column('documentacion', 'anyo')
    # drop enum types if they exist
    mes_enum = sa.Enum(name='mesenum')
    try:
        mes_enum.drop(op.get_bind(), checkfirst=True)
    except Exception:
        pass
    tipo_enum = sa.Enum(name='tipoenum')
    try:
        tipo_enum.drop(op.get_bind(), checkfirst=True)
    except Exception:
        pass
    # ### end Alembic commands ###
