"""add_must_change_password

Revision ID: 62523bba38ac
Revises: ee37ba52b458
Create Date: 2026-02-09 20:45:43.855701

"""
from alembic import op
import sqlalchemy as sa


revision = '62523bba38ac'
down_revision = 'ee37ba52b458'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('must_change_password', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'must_change_password')
    # ### end Alembic commands ###
