"""cambio de obligatoriedad en productos

Revision ID: 6e5f4fe49b6c
Revises: 46966bef146e
Create Date: 2026-07-17 18:59:10.016648

"""
import sqlalchemy as sa

from alembic import op

revision = '6e5f4fe49b6c'
down_revision = '46966bef146e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    inspector = sa.inspect(op.get_bind())
    columns = {column['name']: column for column in inspector.get_columns('sistemas')}
    if 'link' in columns and not columns['link']['nullable']:
        op.alter_column('sistemas', 'link', existing_type=sa.VARCHAR(), nullable=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sistemas', 'link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
