"""cambio de obligatoriedad en productos

Revision ID: 6e5f4fe49b6c
Revises: 46966bef146e
Create Date: 2026-07-17 18:59:10.016648

"""
from alembic import op
import sqlalchemy as sa


revision = '6e5f4fe49b6c'
down_revision = '46966bef146e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sistemas', 'link',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sistemas', 'link',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
