"""add mapas table

Revision ID: 6ef62c2a74a0
Revises: a1b2c3d4e5f6
Create Date: 2026-05-26 17:34:39.342458

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = '6ef62c2a74a0'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


tipomapaenum = postgresql.ENUM(
    'separado', 'atlas', 'libro', 'compuesto', 'casos', 'bolsillo',
    'monumento_hipsografico', 'atlas_catastral_jalisco', 'plano_separado',
    'mapa_grafico', 'carta_topografica', 'carta_geologica',
    'carta_frontera_agricola', 'carta_uso_suelo_vegetacion',
    'edicion_bolsillo_1er', 'carta_municipal', 'mapa_general',
    'carta_general',
    name='tipomapaenum',
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    tipomapaenum.create(op.get_bind(), checkfirst=True)
    op.add_column('mapa', sa.Column('tipo', tipomapaenum, nullable=True))
    op.add_column('mapa', sa.Column('area', sa.String(), nullable=True))
    op.alter_column('mapa', 'edicion',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mapa', 'edicion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('mapa', 'area')
    op.drop_column('mapa', 'tipo')
    tipomapaenum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
