"""update

Revision ID: 76c619d9360c
Revises: a7c9e22b8f4b
Create Date: 2026-06-17 19:21:54.131306

"""


revision = '76c619d9360c'
down_revision = 'a7c9e22b8f4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
