"""add_publication_requests

Revision ID: ee37ba52b458
Revises: 001
Create Date: 2026-02-09 20:37:10.861531

"""
from alembic import op
import sqlalchemy as sa


revision = 'ee37ba52b458'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publication_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='publication_status'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publication_requests_id'), 'publication_requests', ['id'], unique=False)
    op.create_index(op.f('ix_publication_requests_resource_type'), 'publication_requests', ['resource_type'], unique=False)
    op.create_index(op.f('ix_publication_requests_status'), 'publication_requests', ['status'], unique=False)
    op.create_index(op.f('ix_publication_requests_user_id'), 'publication_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publication_requests_user_id'), table_name='publication_requests')
    op.drop_index(op.f('ix_publication_requests_status'), table_name='publication_requests')
    op.drop_index(op.f('ix_publication_requests_resource_type'), table_name='publication_requests')
    op.drop_index(op.f('ix_publication_requests_id'), table_name='publication_requests')
    op.drop_table('publication_requests')
    # ### end Alembic commands ###
