"""add_publication_requests

Revision ID: ee37ba52b458
Revises: 001
Create Date: 2026-02-09 20:37:10.861531

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = 'ee37ba52b458'
down_revision = 'f3a8b2c1d9e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'publication_status') THEN
            CREATE TYPE publication_status AS ENUM ('pending', 'approved', 'rejected');
        END IF;
    END$$;
    """)
    inspector = sa.inspect(op.get_bind())
    if 'publication_requests' not in inspector.get_table_names():
        status_enum = postgresql.ENUM(
            'pending', 'approved', 'rejected',
            name='publication_status', create_type=False,
        )
        op.create_table(
            'publication_requests',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('resource_type', sa.String(length=50), nullable=False),
            sa.Column('draft_id', sa.Integer(), nullable=False),
            sa.Column('status', status_enum, nullable=False),
            sa.Column('rejection_reason', sa.Text(), nullable=True),
            sa.Column('reviewed_by', sa.Integer(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.Column('reviewed_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['draft_id'], ['borradores.id'], ),
            sa.ForeignKeyConstraint(['reviewed_by'], ['usuarios.id'], ),
            sa.ForeignKeyConstraint(['user_id'], ['usuarios.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    op.execute('CREATE INDEX IF NOT EXISTS ix_publication_requests_id ON publication_requests (id)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_publication_requests_resource_type ON publication_requests (resource_type)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_publication_requests_status ON publication_requests (status)')
    op.execute('CREATE INDEX IF NOT EXISTS ix_publication_requests_user_id ON publication_requests (user_id)')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_publication_requests_user_id'), table_name='publication_requests')
    op.drop_index(op.f('ix_publication_requests_status'), table_name='publication_requests')
    op.drop_index(op.f('ix_publication_requests_resource_type'), table_name='publication_requests')
    op.drop_index(op.f('ix_publication_requests_id'), table_name='publication_requests')
    op.drop_table('publication_requests')
    # ### end Alembic commands ###
