"""updateexit

Revision ID: ffcbb95dc8bb
Revises: 76c619d9360c
Create Date: 2026-06-17 19:22:19.165178

"""
from alembic import op
import sqlalchemy as sa


revision = 'ffcbb95dc8bb'
down_revision = '76c619d9360c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
