import enum
from sqlalchemy import Column, Integer, String, Enum
from app.core.database import Base


class MunicipioEnum(str, enum.Enum):
    acatic = "Acatic"
    acatlan_de_juarez = "Acatlán de Juárez"
    ahualulco_de_mercado = "Ahualulco de Mercado"
    amacoeca = "Amacueca"
    amatitan = "Amatitán"
    ameca = "Ameca"
    arandas = "Arandas"
    atengo = "Atengo"
    atenguillo = "Atenguillo"
    atotonilco_el_alto = "Atotonilco el Alto"
    atoyac = "Atoyac"
    autlan_de_navarro = "Autlán de Navarro"
    ayotlan = "Ayotlán"
    ayutla = "Ayutla"
    bolanos = "Bolaños"
    cabo_corrientes = "Cabo Corrientes"
    casimiro_castillo = "Casimiro Castillo"
    chapala = "Chapala"
    chimaltitan = "Chimaltitán"
    chiquilistlan = "Chiquilistlán"
    cihuatlan = "Cihuatlán"
    cocula = "Cocula"
    colotlan = "Colotlán"
    concepcion_de_buenos_aires = "Concepción de Buenos Aires"
    cuautitlan_de_garcia_barragan = "Cuautitlán de García Barragán"
    cuautla = "Cuautla"
    quiquio = "Cuquío"
    degollado = "Degollado"
    ejutla = "Ejutla"
    el_arenal = "El Arenal"
    el_grullo = "El Grullo"
    el_limon = "El Limón"
    el_salto = "El Salto"
    encarnacion_de_diaz = "Encarnación de Díaz"
    gomez_farias = "Gómez Farías"
    guachinango = "Guachinango"
    hostotipaquillo = "Hostotipaquillo"
    huejucar = "Huejúcar"
    huejuquilla_el_alto = "Huejuquilla el Alto"
    la_barca = "La Barca"
    la_manzanilla_de_la_paz = "La Manzanilla de la Paz"
    la_huerta = "La Huerta"
    lagos_de_moreno = "Lagos de Moreno"
    magdalena = "Magdalena"
    mascota = "Mascota"
    mazamitla = "Mazamitla"
    mexticacan = "Mexticacán"
    mezquitic = "Mezquitic"
    mixtlan = "Mixtlán"
    ocotlan = "Ocotlán"
    ojuelos_de_jalisco = "Ojuelos de Jalisco"
    pihuamo = "Pihuamo"
    poncitlan = "Poncitlán"
    puerto_vallarta = "Puerto Vallarta"
    villa_purificacion = "Villa Purificación"
    quitupan = "Quitupan"
    san_cristobal_de_la_barranca = "San Cristóbal de la Barranca"
    san_diego_de_alejandria = "San Diego de Alejandría"
    san_juan_de_los_lagos = "San Juan de los Lagos"
    san_juanito_de_escobedo = "San Juanito de Escobedo"
    san_julian = "San Julián"
    san_marcos = "San Marcos"
    san_martin_de_bolanos = "San Martín de Bolaños"
    san_martin_hidalgo = "San Martín Hidalgo"
    san_miguel_el_alto = "San Miguel el Alto"
    san_patricio_melaque = "Cihuatlán" # (Nota: Melaque pertenece a Cihuatlán)
    san_sebastian_el_oeste = "San Sebastián del Oeste"
    santa_maria_de_los_angeles = "Santa María de los Ángeles"
    santa_maria_del_oro = "Santa María del Oro"
    sayula = "Sayula"
    tala = "Tala"
    talpa_de_allende = "Talpa de Allende"
    tamazula_de_gordiano = "Tamazula de Gordiano"
    tapalpa = "Tapalpa"
    tecalitlan = "Tecalitlán"
    techaluta_de_montenegro = "Techaluta de Montenegro"
    tecolotlan = "Tecolotlán"
    tenamaxtlan = "Tenamaxtlán"
    teocaltiche = "Teocaltiche"
    teocuitatlan_de_corona = "Teocuitatlán de Corona"
    tepatitlan_de_morelos = "Tepatitlán de Morelos"
    tequila = "Tequila"
    teuchitlan = "Teuchitlán"
    tizapan_el_alto = "Tizapán el Alto"
    toliman = "Tolimán"
    tomatlan = "Tomatlán"
    tonaya = "Tonaya"
    tonila = "Tonila"
    totatiche = "Totatiche"
    tototlan = "Tototlán"
    tuxcacuesco = "Tuxcacuesco"
    tuxcueca = "Tuxcueca"
    tuxpan = "Tuxpan"
    union_de_san_antonio = "Unión de San Antonio"
    union_de_tula = "Unión de Tula"
    valle_de_guadalupe = "Valle de Guadalupe"
    valle_de_juarez = "Valle de Juárez"
    villa_corona = "Villa Corona"
    villa_guerrero = "Villa Guerrero"
    villa_hidalgo = "Villa Hidalgo"
    cañadas_de_obregon = "Cañadas de Obregón"
    yahualica_de_gonzalez_gallo = "Yahualica de González Gallo"
    zacoalco_de_torres = "Zacoalco de Torres"
    zafiro = "Cuautitlán" # (Nota: El Zapote / Zafiro se integran en sus respectivos municipios)
    zapotiltic = "Zapotiltic"
    zapotitlan_de_vadillo = "Zapotitlán de Vadillo"
    zapotlan_del_rey = "Zapotlán del Rey"
    zapotlanejo = "Zapotlanejo"
    san_gabriel = "San Gabriel"
    zapotlan_el_grande = "Zapotlán el Grande"

    
class Cuadernillo(Base):
    __tablename__ = "cuadernillos"

    id = Column(Integer, primary_key=True, index=True)
    titulo = Column(String(200), nullable=False)
    archivo = Column(String(200), nullable=True)
    municipio = Column(Enum(MunicipioEnum), nullable=True)
    anyo = Column(Integer, nullable=True)
    slug = Column(String(200), nullable=True)