#!/usr/bin/env bash
set -euo pipefail

: "${CKAN_DB_USER:?CKAN_DB_USER is required}"
: "${CKAN_DB_PASSWORD:?CKAN_DB_PASSWORD is required}"
: "${DATASTORE_RO_USER:?DATASTORE_RO_USER is required}"
: "${DATASTORE_RO_PASSWORD:?DATASTORE_RO_PASSWORD is required}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${CKAN_DB_USER} WITH PASSWORD '${CKAN_DB_PASSWORD}';
    CREATE DATABASE ckan_default OWNER ${CKAN_DB_USER} ENCODING 'UTF8';

    CREATE USER ${DATASTORE_RO_USER} WITH PASSWORD '${DATASTORE_RO_PASSWORD}';
    CREATE DATABASE datastore_default OWNER ${CKAN_DB_USER} ENCODING 'UTF8';

    GRANT ALL PRIVILEGES ON DATABASE ckan_default TO ${CKAN_DB_USER};
    GRANT ALL PRIVILEGES ON DATABASE datastore_default TO ${CKAN_DB_USER};
    GRANT CONNECT ON DATABASE datastore_default TO ${DATASTORE_RO_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "datastore_default" <<-EOSQL
    REVOKE CREATE ON SCHEMA public FROM PUBLIC;
    REVOKE USAGE ON SCHEMA public FROM PUBLIC;

    GRANT CREATE ON SCHEMA public TO ${CKAN_DB_USER};
    GRANT USAGE ON SCHEMA public TO ${CKAN_DB_USER};

    GRANT CREATE ON SCHEMA public TO ${DATASTORE_RO_USER};
    GRANT USAGE ON SCHEMA public TO ${DATASTORE_RO_USER};
EOSQL
