[metadata]
name = ckanext-iieg-theme
version = 0.1.0
description = Tema personalizado para el portal IIEG
long_description = file: README.md
long_description_content_type = text/markdown
author = IIEG
author_email = admin@iieg.gob.mx
license = AGPL
classifiers =
    Development Status :: 4 - Beta
    License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3.10

[options]
packages = find:
python_requires = >=3.8
install_requires =
    ckan>=2.11

[options.extras_require]
dev =
    pytest-ckan

[options.entry_points]
ckan.plugins =
    iieg_theme = ckanext.iieg_theme.plugin:IiegThemePlugin

[flake8]
max-line-length = 120

[extract_messages]
keywords = translate isPlural _ ungettext ngettext gettext
add_comments = TRANSLATORS:
output_file = ckanext/iieg_theme/i18n/ckanext-iieg_theme.pot
width = 80
mapping_file = babel.cfg

[init_catalog]
domain = ckanext-iieg_theme
input_file = ckanext/iieg_theme/i18n/ckanext-iieg_theme.pot
output_dir = ckanext/iieg_theme/i18n

[update_catalog]
domain = ckanext-iieg_theme
input_file = ckanext/iieg_theme/i18n/ckanext-iieg_theme.pot
output_dir = ckanext/iieg_theme/i18n

[compile_catalog]
domain = ckanext-iieg_theme
directory = ckanext/iieg_theme/i18n
statistics = true
